task: simulate pre-deployment failure to test pushover notification

diff --git a/.github/workflows/deploy-homelab.yaml b/.github/workflows/deploy-homelab.yaml
--- a/.github/workflows/deploy-homelab.yaml
+++ b/.github/workflows/deploy-homelab.yaml
@@ -161,6 +161,13 @@ jobs:
           install -m 600 -D /dev/null ~/.ssh/lxc_ed25519
           echo "${{ secrets.LXC_SSH_PRIVATE_KEY }}" > ~/.ssh/lxc_ed25519
 
+      - name: Simulate failure (REMOVE AFTER TESTING)
+        if: github.ref == 'refs/heads/main' && steps.check-for-changes.outcome == 'failure'
+        run: |
+          echo "Simulating failure for testing..."
+          sleep 5
+          exit 1
+
       - name: Join Tailscale network
         if: github.ref == 'refs/heads/main' && steps.check-for-changes.outcome == 'failure'
         uses: tailscale/github-action@v4
@@ -169,27 +176,19 @@ jobs:
           oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
           tags: tag:github-actions
 
-      - name: Simulate deployment failure (REMOVE AFTER TESTING)
+      - name: Pulumi up
         if: github.ref == 'refs/heads/main' && steps.check-for-changes.outcome == 'failure'
+        uses: pulumi/actions@v6
         id: pulumi-up
-        run: |
-          echo "Simulating deployment failure for testing..."
-          sleep 5
-          exit 1
-
-      # - name: Pulumi up
-      #   if: github.ref == 'refs/heads/main' && steps.check-for-changes.outcome == 'failure'
-      #   uses: pulumi/actions@v6
-      #   id: pulumi-up
-      #   with:
-      #     command: up
-      #     stack-name: homelab
-      #     comment-on-pr: false
-      #     work-dir: ./
-      #   env:
-      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
-      #     PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          command: up
+          stack-name: homelab
+          comment-on-pr: false
+          work-dir: ./
+        env:
+          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
+          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Send deployment status to Pushover
         if: always() && github.ref == 'refs/heads/main' && steps.check-for-changes.outcome == 'failure'
